### ISSUE TITLE
SoftwareSystems-SQLite-MemSafety is empty

### ISSUE THREAD

**Issue by lembergerth** [sosy-lab/sv-comp#149]
Task set `<tasks name="SoftwareSystems-SQLite-MemSafety">` is empty because it only has a coverage property, so it should not be part of the benchmark definitions.

@dbeyer how to proceed with this? Should every team update its own archives?

**Comment by dbeyer** [comment]
@lembergerth If you could do it and create a pull request that would be great!

Best,
Dirk
