### ISSUE TITLE
Limit number of cores for each verifier

### ISSUE THREAD

**Issue by trucnguyenlam** [sosy-lab/sv-comp#32]
Hi,

I would like to understand why each verification tool is given 2 CPU cores , for example:
`<benchmark tool="aprove" timelimit="900 s" memlimit="15 GB" cpuCores="2">`

while in [https://sv-comp.sosy-lab.org/2017/rules.php](rules), the limitation is different.

> there are three resource limits for each verification run: a memory limit of 15 GB (14.6 GiB) of RAM, a runtime limit of 15 min of CPU time, and a limit to **8 processing units of a CPU**.

Could anyone please clarify this?

Many thanks,
Truc

**Comment by dbeyer** [comment]
The reduced resources are for the test runs. The official SV-COMP runs will be done with 8 processing units, i.e., a full dedicated CPU per verification run.
